### ISSUE TITLE
tab2 give error after 5 patients

### ISSUE THREAD

**Issue by anandgavai** [andi-nl/ANDI-frontend#29] opened 2016-04-25 09:00 UTC
Give error after 5 patients are manually added

**Comment by mkuzak** [comment] 2016-05-09 10:25
Is this the same issue as #19 ?

**Comment by mkuzak** [comment] 2016-05-10 06:54
Actually even though it does not through an error, it does not add another patient.
The comment below `If there exists more than 5 patients. Download this template...` suggests this is expected behavior. What is the reason for limiting number of patients that can be input manually?

**Comment by Nanouk123** [comment] 2016-05-10 07:04
From our end there isnt (in an earlier 'wishlist' I asked for this to be removed).  Clinicians should be able to decide for themselves how much they want to manually type in. Likewise you should be able to upload template data of one single patient.

**Comment by JAvRZ** [comment] 2016-05-10 07:35
The 5 patients limit can be removed; especially if patients addition and deletion is managable with always visible test names. I think five patients may have come up as a theoretical limit of the number of patients that any user may have the patience for to fill them in, and if there is trouble fitting them on the screen, a limit may be necessary. But screen fitting solutions are definitely preferred over arbitrary limits.

**Comment by anandgavai** [comment] 2016-06-01 08:00
I have removed the limit so this can be closed

**Comment by mkuzak** [comment] 2016-06-01 09:20
Fixed in PR #53

**Closed as completed by mkuzak** 2016-06-01 09:20 UTC
Labels: bug
